name: HX Job Status Update Email Script

on:
  workflow_dispatch: # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests snowflake-connector-python pandas
          pip install google-api-python-client

      - name: Run recommender script
        run: python hx.py
